name: Unit Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: npm run common:lint
      - run: npm run generator:lint
      - run: npm run ui:lint
      - run: npm run common:build
      - run: npm run generator:build
      - run: npm run ui:build
      - run: npm run common:test
      - run: npm run generator:test
      - run: npm run ui:test
        env:
          CI: true
